Implement fold expressions and more complete requires clauses
tree-sitter/tree-sitter-cpp pull request #151
Opened 2022-02-06 23:13 UTC by ChewyGumball

Fold Expressions
==========
This PR adds rules to recognize fold expressions.

Example:
```cpp
int t = (... + IndexOf<T>);
```
currently produces an error because the ellipsis is unrecognized:
```
(translation_unit [0, 0] - [0, 27]
  (declaration [0, 0] - [0, 27]
    type: (primitive_type [0, 0] - [0, 3])
    declarator: (init_declarator [0, 4] - [0, 26]
      declarator: (identifier [0, 4] - [0, 5])
      value: (parenthesized_expression [0, 8] - [0, 26]
        (ERROR [0, 9] - [0, 12])
        (unary_expression [0, 13] - [0, 25]
          argument: (template_function [0, 15] - [0, 25]
            name: (identifier [0, 15] - [0, 22])
            arguments: (template_argument_list [0, 22] - [0, 25]
              (type_descriptor [0, 23] - [0, 24]
                type: (type_identifier [0, 23] - [0, 24])))))))))
```

but with this PR, the ellipsis is recognized and produces a `fold_expression` node:
```
(translation_unit [0, 0] - [0, 27]
  (declaration [0, 0] - [0, 27]
    type: (primitive_type [0, 0] - [0, 3])
    declarator: (init_declarator [0, 4] - [0, 26]
      declarator: (identifier [0, 4] - [0, 5])
      value: (fold_expression [0, 8] - [0, 26]
        (template_function [0, 15] - [0, 25]
          name: (identifier [0, 15] - [0, 22])
          arguments: (template_argument_list [0, 22] - [0, 25]
            (type_descriptor [0, 23] - [0, 24]
              type: (type_identifier [0, 23] - [0, 24]))))))))
```

The other three types of fold expressions are improved in similar ways:
```cpp
int t = (IndexOf<T> + ...);
int t = (1 + ... + IndexOf<T>);
int t = (IndexOf<T> + ... + 1);
```

Requires Clauses
==========
The current support for a requires clause only works for a single template/concept name or a requires expression, but does not support boolean expressions, or other expressions as outlined on [cppreference.com](https://en.cppreference.com/w/cpp/language/constraints):

- a [primary expression](https://en.cppreference.com/w/cpp/language/expressions#Primary_expressions), e.g. Swappable<T>, [std::is_integral](http://en.cppreference.com/w/cpp/types/is_integral)<T>::value, ([std::is_object_v](http://en.cppreference.com/w/cpp/types/is_object)<Args> && ...), or any parenthesized expression
- a sequence of primary expressions joined with the operator &&
- a sequence of aforementioned expressions joined with the operator ||

where a primary expression is defined as (again from [cppreference.com](https://en.cppreference.com/w/cpp/language/expressions#Primary_expressions)):
- Literals (e.g. 2 or "Hello, world")
- Id-expressions, including
        suitably declared [unqualified identifiers](https://en.cppreference.com/w/cpp/language/identifiers#Unqualified_identifiers) (e.g. n or cout), and
        suitably declared [qualified identifiers](https://en.cppreference.com/w/cpp/language/identifiers#Qualified_identifiers) (e.g. [std::string::npos](https://en.cppreference.com/w/cpp/string/basic_string/npos)) 
- [Lambda-expressions](https://en.cppreference.com/w/cpp/language/lambda) (since C++11)
- [Fold-expressions](https://en.cppreference.com/w/cpp/language/fold) (since C++17)
- [Requires-expressions](https://en.cppreference.com/w/cpp/language/constraints) (since C++20)

I'm not sure if some of these things have much use in a requires clause (what does `requires "Hello, world"` mean?), but this PR upgrades the grammar to accept lambda expressions, fold expressions, any parenthesized expression, boolean literals, and conjunctions/disjunctions.

Example:
```cpp
template<typename T> requires (!std::is_same_v<T, bool>) T f2(T);
```
currently produces errors from the parentheses and negation part of the expression:
```
(translation_unit [0, 0] - [0, 64]
  (template_declaration [0, 0] - [0, 64]
    parameters: (template_parameter_list [0, 8] - [0, 20]
      (type_parameter_declaration [0, 9] - [0, 19]
        (type_identifier [0, 18] - [0, 19])))
    (requires_clause [0, 21] - [0, 54]
      (ERROR [0, 29] - [0, 31])
      constraint: (qualified_identifier [0, 31] - [0, 54]
        scope: (namespace_identifier [0, 31] - [0, 34])
        name: (template_type [0, 36] - [0, 54]
          name: (type_identifier [0, 36] - [0, 45])
          arguments: (template_argument_list [0, 45] - [0, 54]
            (identifier [0, 46] - [0, 47])
            (type_descriptor [0, 49] - [0, 53]
              type: (primitive_type [0, 49] - [0, 53]))))))
    (ERROR [0, 54] - [0, 55])
    (declaration [0, 56] - [0, 64]
      type: (type_identifier [0, 56] - [0, 57])
      declarator: (function_declarator [0, 58] - [0, 63]
        declarator: (identifier [0, 58] - [0, 60])
        parameters: (parameter_list [0, 60] - [0, 63]
          (parameter_declaration [0, 61] - [0, 62]
            type: (type_identifier [0, 61] - [0, 62])))))))
```

but with this PR, everything is recognized nicely:
```
(translation_unit [0, 0] - [0, 64]
  (template_declaration [0, 0] - [0, 64]
    parameters: (template_parameter_list [0, 8] - [0, 20]
      (type_parameter_declaration [0, 9] - [0, 19]
        (type_identifier [0, 18] - [0, 19])))
    (requires_clause [0, 21] - [0, 55]
      constraint: (unary_expression [0, 30] - [0, 54]
        argument: (qualified_identifier [0, 31] - [0, 54]
          scope: (namespace_identifier [0, 31] - [0, 34])
          name: (template_function [0, 36] - [0, 54]
            name: (identifier [0, 36] - [0, 45])
            arguments: (template_argument_list [0, 45] - [0, 54]
              (type_descriptor [0, 46] - [0, 47]
                type: (type_identifier [0, 46] - [0, 47]))
              (type_descriptor [0, 49] - [0, 53]
                type: (primitive_type [0, 49] - [0, 53])))))))
    (declaration [0, 56] - [0, 64]
      type: (type_identifier [0, 56] - [0, 57])
      declarator: (function_declarator [0, 58] - [0, 63]
        declarator: (identifier [0, 58] - [0, 60])
        parameters: (parameter_list [0, 60] - [0, 63]
          (parameter_declaration [0, 61] - [0, 62]
            type: (type_identifier [0, 61] - [0, 62])))))))
```

2022-02-17 16:10 UTC, jdrouhard requested changes
Looks pretty good to me. Having the list of FOLD_OPERATORS at the top is a bit different than the other places we've needed lists of operators (take a look at the c grammar's binary_expression rule, and this grammar's operator rule).

I see you need it since you create two rules out of the list, and I also couldn't think of anyway to reuse existing operator lists since they aren't quite the same.

Otherwise, just a few small comments.

2022-02-17 16:10 UTC, jdrouhard commented on grammar.js
> +    _unary_right_fold: $ => seq('...', $._fold_operator, $._expression),
For all three of these folds, can you add `field()` labels to the `...`, operator, and expression like normal `binary_expression`s do?

For binary folds, I wonder whether we label the entire "middle part" (`op .. op`) as one, or the individual pieces...not sure I have a strong opinion on that one.

2022-02-17 16:11 UTC, jdrouhard commented
Fixes #21

2022-02-19 17:47 UTC, ChewyGumball commented on grammar.js
>      ),
Ah, good catch. I needed this in a previous version of how I specified fold expressions to remove ambiguities, but with the current grammar it isn't necessary. I've removed this change.

2022-02-19 22:36 UTC, jdrouhard requested changes
Thanks for addressing my comments! As a last step, could you rebase your changes into one commit? The huge parser deltas between each commit make these git histories pretty large.

2022-02-20 05:56 UTC, ChewyGumball commented
I believe if you select the "Squash and merge" option when merging the PR, it will combine them all into one commit on the target branch. If that's not possible, let me know and I will manually squash them.

2022-02-20 13:53 UTC, jdrouhard commented
Of course I can do that through the GitHub PR interface. 🤣

2022-02-20 13:54 UTC, merged